In [3]:
import torch
from torch import nn
import numpy as np

In [ ]:
class PyramidFeatures(nn.Module):
    def __init__(C3_size, C4_size, C5_size, feature_size=256):
        super().__init__()
        
        self.

In [7]:
scales = np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)])
ratios = np.array([0.5, 1, 2])
base_size = 16
num_anchors = len(ratios) * len(scales)
anchors = np.zeros((num_anchors, 4))
print(np.tile(scales, (2, len(ratios))).T)
anchors[:, 2:] = base_size * np.tile(scales, (2, len(ratios))).T
print(anchors)


[[1.         1.        ]
 [1.25992105 1.25992105]
 [1.58740105 1.58740105]
 [1.         1.        ]
 [1.25992105 1.25992105]
 [1.58740105 1.58740105]
 [1.         1.        ]
 [1.25992105 1.25992105]
 [1.58740105 1.58740105]]
[[ 0.          0.         16.         16.        ]
 [ 0.          0.         20.1587368  20.1587368 ]
 [ 0.          0.         25.39841683 25.39841683]
 [ 0.          0.         16.         16.        ]
 [ 0.          0.         20.1587368  20.1587368 ]
 [ 0.          0.         25.39841683 25.39841683]
 [ 0.          0.         16.         16.        ]
 [ 0.          0.         20.1587368  20.1587368 ]
 [ 0.          0.         25.39841683 25.39841683]]


In [14]:
print(anchors[:, 2])

[16.         20.1587368  25.39841683 16.         20.1587368  25.39841683
 16.         20.1587368  25.39841683]


In [15]:
areas = anchors[:, 2] * anchors[:, 3]
print(areas)

[256.         406.3746693  645.07957755 256.         406.3746693
 645.07957755 256.         406.3746693  645.07957755]


In [16]:
areas.ravel()

array([256.        , 406.3746693 , 645.07957755, 256.        ,
       406.3746693 , 645.07957755, 256.        , 406.3746693 ,
       645.07957755])

In [8]:
np.repeat(ratios, len(scales))

array([0.5, 0.5, 0.5, 1. , 1. , 1. , 2. , 2. , 2. ])