In [3]:
import torch

class BalancedPositiveNegativeSampler(object):
    def __init__(self, batch_size_per_image, positive_fraction):
        self.batch_size_per_image = batch_size_per_image
        self.positive_fraction = positive_fraction
    def __call__(self, matched_idxs):
        
        pos_idx = []
        neg_idx = []
        for matched_idxs_per_image in matched_idxs:
            positive = torch.nonzero(matched_idxs_per_image >= 1).squeeze(1)
            negative = torch.nonzero(matched_idxs_per_image == 0).squeeze(1)

In [20]:
z = torch.randn((4))
print(z)
print(z.shape)
print(z>=0)
z = torch.nonzero(z>=0)
print(z)
print(z.shape)
z = z.squeeze(1)
print(z)
print(z.shape)

tensor([ 1.5912,  1.4064,  0.0952, -0.8204])
torch.Size([4])
tensor([1, 1, 1, 0], dtype=torch.uint8)
tensor([[0],
        [1],
        [2]])
torch.Size([3, 1])
tensor([0, 1, 2])
torch.Size([3])


In [17]:
z = torch.randn((4))
z = z.squeeze(1)
print(z.shape)

torch.Size([4, 5, 1, 1])
